# variables for lib/fax_common_methods/module.rb
username: 'ealzubaidi'
APIkey: '817C7FD99D6146B89BEA88BA5B1E48DE'
vector: 'x49e*wJVXr8BrALE'
encryptionkey: 'gZ!LaHKAmmuXd7AMamtPqIepQ7RMsbJ3'
fax_server_url: 'https://api.sfaxme.com'

# variables for lib/tasks/fax_response.rake
max_fax_response_check_tries: '20'
client_url: 'https://dhp-efax-q.discoveryhealthpartners.com/eFaxService/OutboundDispositionService.svc/receive'

#file service server info

file_service_path: 'http://54.236.45.31'
