development:
  adapter: postgresql
  encoding: UTF8
  database: faxdb4
  host: localhost
  pool: 5
  username: postgres
  password: 19771977

test:
  adapter: postgresql
  encoding: UTF8
  database: faxdb4
  host: localhost
  pool: 5
  username: postgres
  password: 19771977


